### ISSUE TITLE
[nonroot] downloading problem

### ISSUE THREAD

**Issue by LeosProblems** [YTVanced/VancedManager#311] opened 2020-12-14 12:50 UTC
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand:xiaomi redmi note 7
- Operating System:miui12
- Android Version:10
- Vanced Manager Version:latest

**Please describe the problem you are having in as much detail as possible:**
A box pops up when trying to download micro g and it says "Vanced MicroG please be patient..." and on the bottom of the box it says error downloading MicroG

**Steps to reproduce:**
Tap Install on MicroG and the box pops up

**Further details:**
Yes, I have disabled miui optimization.

**Comment by LeosProblems** [comment] 2020-12-14 12:56
![IMG_20201214_135712](https://user-images.githubusercontent.com/75986625/102083639-2f5faf00-3e14-11eb-978c-c46b5cfe98b4.jpg)

**Comment by Maximilian1271** [comment] 2020-12-14 13:03
this is a duplicate of #310

**Comment by LeosProblems** [comment] 2020-12-14 13:15
> this is a duplicate of #310

On #310 they said that micro G could be downloaded though

**Comment by X1nto** [comment] 2020-12-14 13:18
Clear manager data and try again

**Comment by X1nto** [comment] 2020-12-14 13:19
Nevermind, google servers are down

**Closed by X1nto** 2020-12-14 13:19 UTC
