### ISSUE TITLE
[Bug]: The latest vanced manager update can't install YT vanced on MIUI

### ISSUE THREAD

**Issue by Quake-A** [YTVanced/VancedManager#699] opened 2021-10-09 09:09 UTC
### Device

Device: Redmi 9T "Lime"
Operating System: MIUI Global 12.0.17
Android Version: 10 QKQ1.200830.002

### Version

2.6.1

### Bug Description

After getting back to the original MIUI i started by disabling MIUI Optimizations, And i installed Vanced Manager version 2.6.0 as i had the apk from before and when i opened it i got an update notification so i let it update and when i tried to install YT Vanced it kept giving me an error massage that says "Installation failed for unknown reasons" and when i click details it says: "Error: Unable to open file: /data/local/tmp/split_config.arm64_v8a.apk".

It came to me that it's maybe the update that's the reason so i uninstalled Vanced Manager and i installed version 2.6.0 and didn't let it update and tried once more to install YT Vanced root version and it worked perfectly no errors.

PS: It's my first time here on github and this is my first bug report, so sorry if it has anything wrong or if my english is not so good it's not my native language, thanks in advance

### Additional checks

- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by milindgoel15** [comment] 2021-10-09 11:24
Duplicate of #697

**Closed as completed** 2021-10-09 11:28 UTC
Labels: bug
