### ISSUE TITLE
Add ability to install older versions

### ISSUE THREAD

**Issue by theredbaron05** [YTVanced/VancedManager#204] opened 2020-10-11 00:55 UTC
The most recent 2 versions of vanced both crash for me but before that it was fine, it would be really helpful to be able to roll back to a working one. The newest one on the website is 15.05.54 but that one doesn't work so I have to install 14.21.54 so I can't manually install a working recent version either

**Comment by retorquere** [comment] 2020-10-11 19:52
I'd love to see this too. After the latest update, vanced no longer finds my chromecast.

**Comment by X1nto** [comment] 2020-10-12 05:00
Duplicate of #80

**Closed by X1nto** 2020-10-12 05:01 UTC
