### ISSUE TITLE
[Bug]: Error: Unable to open file: /data/local/tmp/split_config.en.apk

### ISSUE THREAD

**Issue by john5788** [YTVanced/VancedManager#698] opened 2021-10-09 05:31 UTC
### Device

Device: Samsung S10e
Operating System: LineageOS 18.1
Android Version: Android 11

### Version

2.6.1

### Bug Description

Tried to install the root version and encountered this error in the logs:

```
VMNetTools: Fetching using URL: https://api.vancedapp.com/api/v1
VMInstall: Checking stock version
VMInstall: Unable to get package info
VMInstall: Installing stock
VMInstall: installing split apk files: [split_config.en.apk, dpi.apk, split_config.arm64_v8a.apk, stock.apk, dark.apk]
VMInstall: installing APK: split_config.en.apk
VMInstall: avc:  denied  { read } for  scontext=u:r:system_server:s0 tcontext=u:object_r:sdcardfs:s0 tclass=file permissive=0 System server has no access to read file context u:object_r:sdcardfs:s0 (from path /data/local/tmp/split_config.en.apk, context u:r:system_server:s0) Error: Unable to open file: /data/local/tmp/split_config.en.apk
VMInstall: Checking stock version
VMInstall: Unable to get package info
VMInstall: Installing stock
VMInstall: installing split apk files: [split_config.arm64_v8a.apk, split_config.en.apk, stock.apk, dpi.apk, dark.apk]
VMInstall: installing APK: split_config.arm64_v8a.apk
VMInstall: avc:  denied  { read } for  scontext=u:r:system_server:s0 tcontext=u:object_r:sdcardfs:s0 tclass=file permissive=0 System server has no access to read file context u:object_r:sdcardfs:s0 (from path /data/local/tmp/split_config.arm64_v8a.apk, context u:r:system_server:s0) Error: Unable to open file: /data/local/tmp/split_config.arm64_v8a.apk

```

### Additional checks

- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by milindgoel15** [comment] 2021-10-09 11:23
Duplicate of #697

**Closed as completed** 2021-10-09 11:28 UTC
Labels: bug
