### ISSUE TITLE
YouTube and YT Music fails to start after reboot

### ISSUE THREAD

**Issue by gjf** [YTVanced/VancedManager#352] opened 2021-01-14 05:28 UTC
**Phone Specifications:**
- Brand: Oneplus 7T Pro
- Operating System: OxygenOS 10.0.13.HD01AA
- Android Version: 10
- Vanced Manager Version: 2.1.0

**Please describe the problem you are having in as much detail as possible:**
After reboot both YouTube Vanced and YT Music fails to start. Reinstall helps but till the next reboot only.

**Steps to reproduce:**
1. Install Vanced Manager.
2. Install YouTube Vanced and YT Music (or don't install them second).
3. Try to start it (it does).
4. Reboot the phone.
5. Try to stay YouTube Vanced or YT Musuc (it doesn't).

**Comment by gghhkm** [comment] 2021-01-14 06:01
You're talking about root version right?
Root won't be fixed until next release.

**Comment by gjf** [comment] 2021-01-14 06:46
> You're talking about root version right?
> Root won't be fixed until next release.

Yes

**Comment by Delphox** [comment] 2021-01-14 22:22
You can also test [the latest debug build](https://github.com/YTVanced/VancedManager/suites/1831476060/artifacts/35360562) to check if it fixes the issue (more info #340 and #322) but keep in mind it might have unexpected instability as it's not yet ready for release.

**Comment by gjf** [comment] 2021-01-16 13:33
Debug version does not install Youtube Vanced at all - it gets stuck in installation process.

**Comment by gjf** [comment] 2021-01-16 16:24
I've made a decision to install nonroot version and test it.
It really looks like root version is not working quite well.

**Comment by Delphox** [comment] 2021-01-16 22:12
> Debug version does not install Youtube Vanced at all - it gets stuck in installation process.

You're on Magisk 21.3 right? It's an issue on Magisk side (see #358, topjohnwu/Magisk#3711, topjohnwu/Magisk#3711), latest version is seriously broken. So either downgrade Magisk to 21.2, or wait for an update.

**Comment by souramoo** [comment] 2021-01-17 02:40
If it helps, you can set your Magisk Manager's custom update channel in the settings to `https://raw.githubusercontent.com/souramoo/magisk_files/canary/canary.json` which will let you downgrade Magisk to the last known canary build before this broke (I just forked the magisk update server repo and rolled it back, thank you version control)

**Comment by X1nto** [comment] 2021-01-17 08:24
Can you guys see if it has been resolved in 2.2

**Comment by souramoo** [comment] 2021-01-17 09:58
Confirmed fixed with latest Canary

**Comment by gjf** [comment] 2021-01-17 11:49
> Can you guys see if it has been resolved in 2.2

Still cannot be installed in root mode with latest Magisk.

**Comment by X1nto** [comment] 2021-01-17 11:57
> > Can you guys see if it has been resolved in 2.2
> 
> Still cannot be installed in root mode with latest Magisk.

Magisk 21.3?

**Comment by gjf** [comment] 2021-01-17 12:59
> > Still cannot be installed in root mode with latest Magisk.
> 
> Magisk 21.3?

Latest = 21.3, correct.

**Comment by souramoo** [comment] 2021-01-17 13:01
> > > Still cannot be installed in root mode with latest Magisk.
> > 
> > 
> > Magisk 21.3?
> 
> Latest = 21.3, correct.

You'll need the **canary** build of Magisk (79140c7) which is the commit that implements the functions to fix the problem

**Comment by gjf** [comment] 2021-01-17 13:05
> You'll need the **canary** build of Magisk (79140c7) which is the commit that implements the functions to fix the problem
Yes, I have read the previous posts.
However Magisk seems more critical for me rather than any media player.
So will stay on nonroot until devs work on solution (I hope).

**Comment by X1nto** [comment] 2021-01-17 13:19
> > > Still cannot be installed in root mode with latest Magisk.
> > 
> > 
> > Magisk 21.3?
> 
> Latest = 21.3, correct.

21.3 won't work because of #358, as suggested by @souramoo, you'll need to use canary build of magisk, or stick to nonroot

**Comment by gjf** [comment] 2021-01-17 15:46
OK, with the latest release of Magisk 21.4 installation of root version was successful - more or less.
The only problem: the installer does not check the presence of Youtube update in /data/app. In my case it caused a conflict so Youtube does not start at all after installation of Youtube Vanced. The solution is to remove all updates of Youtube in Google Market (and to disable autoupdates for it - it is vital or the situation with error after reboot will appear again) and then reinstall Youtube Vanced in Manager.

I have to admit the situation with error after reboot is solved after all these actions. However Youtube in Google Market still wants to be updated - and it's a little bit annoying.

I understand dealing with Google Market notification is quite tricky and could cause problems - but I'm just reporting.

**Comment by X1nto** [comment] 2021-01-17 22:55
> OK, with the latest release of Magisk 21.4 installation of root version was successful - more or less.
> The only problem: the installer does not check the presence of Youtube update in /data/app. In my case it caused a conflict so Youtube does not start at all after installation of Youtube Vanced. The solution is to remove all updates of Youtube in Google Market (and to disable autoupdates for it - it is vital or the situation with error after reboot will appear again) and then reinstall Youtube Vanced in Manager.
> 
> I have to admit the situation with error after reboot is solved after all these actions. However Youtube in Google Market still wants to be updated - and it's a little bit annoying.
> 
> I understand dealing with Google Market notification is quite tricky and could cause problems - but I'm just reporting.

Actually manager does detect current youtube installation and uninstalls it

**Comment by X1nto** [comment] 2021-01-22 13:25
Does anyone still have issues with music and vanced crashing after reboot? if not, then I'll close this issue

**Comment by Crewxx** [comment] 2021-01-23 11:33
Yes, I am still having issue after signin to micro G, fails to start after closing, showing offline. My device is non rooted phone.

**Comment by Crewxx** [comment] 2021-01-23 11:34
> Does anyone still have issues with music and vanced crashing after reboot? if not, then I'll close this issue

Yes, I am still having issue after signin to micro G, fails to start after closing, showing offline. My device is non rooted phone.

**Comment by gghhkm** [comment] 2021-01-23 11:38
> > Does anyone still have issues with music and vanced crashing after reboot? if not, then I'll close this issue
> 
> Yes, I am still having issue after signin to micro G, fails to start after closing, showing offline. My device is non rooted phone.

That's not the issue he was talking about.
He's talking about the Root method completely crashing Root Vanced and Root Music. You have a different issue.

**Comment by X1nto** [comment] 2021-01-23 11:42
> > Does anyone still have issues with music and vanced crashing after reboot? if not, then I'll close this issue
> 
> Yes, I am still having issue after signin to micro G, fails to start after closing, showing offline. My device is non rooted phone.

that's definitely not what I'm talking about. Since no one responded, I'll consider it fixed

**Closed by X1nto** 2021-01-23 11:42 UTC
