### ISSUE TITLE
Update notification settings ignored

### ISSUE THREAD

**Issue by trlkly** [YTVanced/VancedManager#653] opened 2021-08-09 13:46 UTC
I keep getting notifications about there being a new YouTube Music update, even though I have the setting to show YouTube Music Vanced Push Notifications turned off, as well as having disabled showing YTM in the interface. 

I'm glad that you are pushing out new updates every month or so (it seems), but I don't use the product and thus don't really need the notification.

**Comment by X1nto** [comment] 2021-08-09 13:49
Duplicate of #449

**Closed as completed by X1nto** 2021-08-09 13:49 UTC
