### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Rezazahmad** [YTVanced/VancedManager#702] opened 2021-10-09 15:30 UTC
### Device

Device: Xiaomi Poco X3 NFC
Operating System: Android (Miui 12.5.2)
Android Version: 11

### Version

2.6.1

### Bug Description

During the installation on a rooted device :

Error: Unable to open file: /data/local/ tmp/split_config.arm64_v8a.apk

### Additional checks

- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment] 2021-10-10 12:09
duplicate of #697

**Closed as completed by X1nto** 2021-10-10 12:09 UTC
Labels: bug
