### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by iain80** [YTVanced/VancedManager#146] opened 2020-09-12 16:02 UTC
Vanced Manager crashes on start up Google Pixel 4 running Android 11.

**Comment by X1nto** [comment] 2020-09-12 16:04
Duplicate of #115. Just wait for an update

**Comment by X1nto** [comment] 2020-09-24 05:55
https://github.com/YTVanced/VancedManager/releases/tag/1.3.0b

**Comment by benefacto** [comment] 2020-09-24 15:13
> 
> 
> https://github.com/YTVanced/VancedManager/releases/tag/1.3.0b

This link is a 404--the latest publicly visible release is 1.2.0.

**Comment by Merwenus** [comment] 2020-09-27 14:14
Any link for the 1.3 beta version? 1.2 crashes on Mi 10 with weekly xiaomi.eu firmware.

**Comment by X1nto** [comment] 2020-09-27 18:39
https://github.com/YTVanced/VancedManager/releases/tag/1.3.0

**Closed by X1nto** 2020-09-27 18:39 UTC
