### ISSUE TITLE
VancedManager 2.0.0 crashing on init

### ISSUE THREAD

**Issue by valuesw** [YTVanced/VancedManager#244] opened 2020-11-13 22:17 UTC
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server - github
- I am using the latest - version 2.0.0
- This is an issue in the Vanced Manager app (NOT Youtube Vanced) - yes
- This issue keeps re-occurring every time I try - yes even after data wipe and uninstall then install
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: samsung galaxy note 4
- Operating System: android n7 port based on samsung framework
- Android Version: 6.0.1
- Vanced Manager Version: 2.0.0

**Please describe the problem you are having in as much detail as possible:**

`FATAL EXCEPTION: main
Process: com.vanced.manager, PID: 7024
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vanced.manager/com.vanced.manager.ui.WelcomeActivity}: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class ImageView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.access$1100(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class ImageView
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at p.k.f.d()
	at p.k.f.c()
	at com.vanced.manager.ui.fragments.WelcomeFragment.O()
	at androidx.fragment.app.Fragment.j0()
	at p.m.b.r.U(:25)
	at p.m.b.r.a()
	at p.m.b.r.D(:8)
	at p.m.b.r.Z()
	at p.m.b.r.B(:4)
	at p.m.b.r.v()
	at p.m.b.r.U(:30)
	at p.m.b.r.S(:1)
	at p.m.b.r.T()
	at p.m.b.r.v()
	at p.m.b.e.onStart(:2)
	at p.b.c.j.onStart()
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java)
	at android.app.Activity.performStart(Activity.java)
	... 10 more
Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class ImageView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	... 30 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_launch_text.xml from drawable resource ID #0x7f08009b
	at android.content.res.Resources.loadDrawableForCookie(Resources.java)
	at android.content.res.Resources.loadDrawable(Resources.java)
	at android.content.res.Resources.loadDrawable(Resources.java)
	at android.content.res.TypedArray.getDrawable(TypedArray.java)
	at android.widget.ImageView.<init>(ImageView.java)
	at android.widget.ImageView.<init>(ImageView.java)
	at p.b.i.n.<init>()
	at p.b.c.m.onCreateView(:10)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java)
	... 34 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/$ic_launch_text__0.xml from color state list resource ID #0x7f080006
	at android.content.res.Resources.loadColorStateListForCookie(Resources.java)
	at android.content.res.Resources.loadColorStateList(Resources.java)
	at android.content.res.TypedArray.getColor(TypedArray.java)
	at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java)
	at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java)
	at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java)
	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java)
	... 43 more
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #13: invalid color state list tag gradient
	at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java)
	at android.content.res.ColorStateList.createFromXml(ColorStateList.java)
	... 52 more`

**Steps to reproduce:**

**Further details:**

**Comment by DanteKG** [comment] 2020-11-13 22:37
Duplicate of #238

**Comment by Cee123** [comment] 2020-11-14 02:48
I came here just to post this as well, can confirm this also crashes on my Android QBox with Android version 5.1.1.

**Comment by AdityaAdi1103** [comment] 2020-11-14 09:04
Same here on android 6.1

**Comment by RaveZero** [comment] 2020-11-14 09:22
Same problem on Note 3 and Amazon Fire HD 10

**Comment by xocox** [comment] 2020-11-14 10:41
Amazon fire with Cyanogenmod Android 5.1 :( same device but with Android 7 works fine but that android version is so buggy for this tablet

**Comment by shom13** [comment] 2020-11-14 16:36
Yes same for me, so switched back to older version for now and that works, but ver 2 crashes immediately after start

**Comment by wjk82** [comment] 2020-11-14 16:40
Yes, I can confirm this bug is real.

**Comment by seba2282** [comment] 2020-11-15 01:16
Me have other problem. After update / clean install Vanced manager 2.0.0 when i take open, then on moment show me window with icon vanced manager and after fast closed automatically app. I can't make nothing. My Huawei P8 Lite 2015 Android 6.0.1

**Comment by Menelwenn** [comment] 2020-11-15 03:09
Same stuff, crashing on boot.

Samsung J3 2016 - Android 5.1.1

Logcat : https://hastebin.com/etijejemak.yaml

**Comment by TRI99ERED** [comment] 2020-11-15 22:58
Same

**Comment by X1nto** [comment] 2020-11-16 13:39
New version released

**Closed by X1nto** 2020-11-16 13:39 UTC

**Comment by seba2282** [comment] 2020-11-16 17:27
Thank you 🙂
