### ISSUE TITLE
Access to api forbidden

### ISSUE THREAD

**Issue by dkweva01007** [YTVanced/VancedManager#646] opened 2021-08-09 06:18 UTC
Hi,
I have a issue with the manager. I can use the API for update youtube/youtube music if I'm used 4G connectiin but I can't if I'm used Wifi connection. 

**Phone Specifications:**
- Brand: Oneplus AA6010
- Operating System: OxygenOS 10.3.12
- Android Version: 10
- Vanced Manager Version: 2.6.0
- GSM Operator: Free Moble
- High Speed Broadband : SFR

![Screenshot_20210809-081746](https://user-images.githubusercontent.com/12497226/128666565-7a14e183-f959-4405-ba38-6da8f9515d44.jpg)

![Screenshot_20210809-081430](https://user-images.githubusercontent.com/12497226/128666606-00470dce-681d-4249-b1d7-f6c4f47b8c2c.jpg)

**Comment by agret** [comment] 2021-08-09 06:47
Duplicate of #645, #644 

The server is overloaded from everyone trying to update at once. Try again in a few hrs and it should be okay.

 #528 is proposed fix for this issue.

**Closed as completed** 2021-08-09 06:49 UTC
