### ISSUE TITLE
[Bug]: Installation failed for unknown reason

### ISSUE THREAD

**Issue by Spackk** [YTVanced/VancedManager#701] opened 2021-10-09 14:42 UTC
### Device

Device: Poco x3 NFC
Operating System: android
Android Version:11 RKQ1.200826.002

### Version

Latest version

### Bug Description

Ibstallation failed for unknown reason. When I open the details option it shows this 
![Screenshot_2021-10-09-17-35-48-748_com vanced manager](https://user-images.githubusercontent.com/92219668/136662665-174b4a9e-2f3e-42f6-950b-c5a4a3951efd.jpg)
Tried rebooting phone, re installed vanced manager too. Any ideas?

### Additional checks

- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment] 2021-10-10 12:09
duplicate of #346

**Closed as completed by X1nto** 2021-10-10 12:09 UTC
Labels: bug
