### ISSUE TITLE
Vanced Manager Crash

### ISSUE THREAD

**Issue by DeZ-Dew** [YTVanced/VancedManager#143] opened 2020-09-08 22:38 UTC
Vanced Manager currently crashing since updating Pixel to Android 11.

**Comment by JamieBrassel** [comment] 2020-09-08 23:43
I'm having the same issue. Here is the error:
`09-08 19:42:35.080 23885 23885 E AndroidRuntime: FATAL EXCEPTION: main
09-08 19:42:35.080 23885 23885 E AndroidRuntime: Process: com.vanced.manager, PID: 23885
09-08 19:42:35.080 23885 23885 E AndroidRuntime: java.lang.ExceptionInInitializerError
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        at o.a0.<init>(:50)
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        at e.d.a.q.i.b.e(:1)
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        at e.d.a.q.i.b.c(Unknown Source:0)
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        at com.vanced.manager.core.App.onCreate(:18)
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7656)
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-08 19:42:35.080 23885 23885 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        at o.n0.h.e.<clinit>(:1)
09-08 19:42:35.080 23885 23885 E AndroidRuntime:        ... 14 more`

**Comment by NatoBoram** [comment] 2020-09-09 00:12
Duplicate of https://github.com/YTVanced/VancedManager/issues/115

**Comment by chowder3907** [comment] 2020-09-19 04:31
I have the exact same issue

**Comment by X1nto** [comment] 2020-09-24 05:56
https://github.com/YTVanced/VancedManager/releases/tag/1.3.0b

**Closed** 2020-09-27 18:40 UTC
