### ISSUE TITLE
Error downloading dark.apk again

### ISSUE THREAD

**Issue by mvfsullivan** [YTVanced/VancedManager#584] opened 2021-06-14 19:18 UTC
**Phone Specifications:**
- Brand: OnePlus
- Operating System: Android
- Android Version: 10
- Vanced Manager Version: 2.6.0

Downloaded Vanced Manager from vancedapp, opened, tried to download and it gives me error. I am running a ROM but I doubt that has to do with anything. What can be done?

**Steps to reproduce:**
Download apk, go through setup, allow root, attempt download

**Further details:**
No further details

Edit: Small typos

**Comment by X1nto** [comment] 2021-06-14 19:21
duplicate of #582

**Closed as completed by X1nto** 2021-06-14 19:21 UTC
