### ISSUE TITLE
[Bug]: Failed to install YouTube

### ISSUE THREAD

**Issue by banana-suisei** [YTVanced/VancedManager#704] opened 2021-10-10 02:22 UTC
### Device

Device: BZT-W09
Operating System: crdroid 7.1
Android Version:11

### Version

2.6.1

### Bug Description

Installing YouTube in root mode failed.

log:
VMNetTools: Fetching using URL: https://api.vancedapp.com/api/v1
VMInstall: Checking stock version
VMInstall: Unable to get package info
VMInstall: Installing stock
VMInstall: installing split apk files: [dark.apk, split_config.arm64_v8a.apk, stock.apk, dpi.apk, split_config.zh.apk]
VMInstall: installing APK: split_config.arm64_v8a.apk
VMInstall: avc:  denied  { read } for  scontext=u:r:system_server:s0 tcontext=u:object_r:sdcardfs:s0 tclass=file permissive=0 System server has no access to read file context u:object_r:sdcardfs:s0 (from path /data/local/tmp/split_config.arm64_v8a.apk, context u:r:system_server:s0) Error: Unable to open file: /data/local/tmp/split_config.arm64_v8a.apk

### Additional checks

- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by camgaertner** [comment] 2021-10-10 05:09
+1
OnePlus 5T
Android 11 / Lineage 18.1

**Comment by touste** [comment] 2021-10-10 11:19
Same here
Android 11
Pixel 4a stock rom

**Comment by jaepizzle** [comment] 2021-10-10 11:37
Same here 
Android 11 
Redmi note 8

**Comment by jaepizzle** [comment] 2021-10-10 11:38
Same here 
Android 11 
Redmi note 8 on evolution x

**Comment by X1nto** [comment] 2021-10-10 12:09
duplicate of #697

**Closed as completed by X1nto** 2021-10-10 12:09 UTC
Labels: bug
