### ISSUE TITLE
Latest version does not open on Google Pixel 3a running Android 11

### ISSUE THREAD

**Issue by Gestrid** [YTVanced/VancedManager#142] opened 2020-09-08 22:35 UTC
Version 1.2.0 seems to have some sort of bug in it that's causing it to crash on my Pixel 3a.  Android 11 came out today for all supported Pixel devices (2, 3, 3a, 4, and 4a), so I performed the update on my phone.  I tried opening Vanced Manager to see if there were any updates for Vanced and microg because of Android 11, but it simply crashed to whatever screen it was on when I tried to open it.  If I was in recent apps, it would crash back to recent apps.  If I was in the app drawer, it'd crash back to the app drawer.  Etc.

Downgrading to v1.0.2 seems to have fixed the issue.  I haven't tried reinstalling Vanced or microg in case those break from using an older version of Vanced Manager combined with issues caused by Android 11, but trying to open the changelog causes Vanced Manager to crash.

Before downgrading, I tried reinstalling the latest version, uninstalling and _then_ reinstalling the latest version, and clearing the cache, all to no avail.

**Comment by NatoBoram** [comment] 2020-09-09 00:12
Duplicate of https://github.com/YTVanced/VancedManager/issues/115

**Comment by X1nto** [comment] 2020-09-24 05:56
https://github.com/YTVanced/VancedManager/releases/tag/1.3.0b

**Comment by Raingram** [comment] 2020-09-26 09:17
> https://github.com/YTVanced/VancedManager/releases/tag/1.3.0b

That link is broken. There's no releases tab enabled for the public.

**Comment by KevinX8** [comment] 2020-09-27 18:40
fixed in https://github.com/YTVanced/VancedManager/releases/tag/1.3.0

**Closed by KevinX8** 2020-09-27 18:40 UTC
