### ISSUE TITLE
Vanced manager cannot update 

### ISSUE THREAD

**Issue by bioinfouser** [YTVanced/VancedManager#232] opened 2020-11-13 07:01 UTC
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: samsung s7, tab s7
- Operating System: Android
- Android Version: 8, 10
- Vanced Manager Version: 1.3.1

**Please describe the problem you are having in as much detail as possible:**
I am trying to update YouTube music. It is failing. I suspect it is trying to fetch data from vanced.app but now you moved the repo to vancedapp.com, that's why maybe it is failing

**Steps to reproduce:**
Open the events Manager app, click the update button

**Further details:**
Vanced

**Comment by X1nto** [comment] 2020-11-13 07:03
Duplicate of #228

**Closed by X1nto** 2020-11-13 07:04 UTC
