### ISSUE TITLE
[Feature]: add this app manager to fdroid

### ISSUE THREAD

**Issue by CodeCubeNeo** [YTVanced/VancedManager#790] opened 2022-02-13 17:03 UTC
### Suggestion

I think you could add this app to the fdroid repository. Here is the link https://f-droid.org/en/contribute/ (under Submit Applications). Really awesome project btw.

### Additional Information

I think it would help spread the app, more people would discovere it, and it would be easier to install.

### Additional checks

- [X] I have checked other feature requests and this is not a duplicate.
- [X] This is a suggestion for Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by RealKasumi** [comment] 2022-02-13 17:06
F-Droid focuses on free and open-source applications.
Vanced is based on stock YT, which is closed source.
So nope.

**Comment by X1nto** [comment] 2022-02-13 17:34
You did not check for duplicates. Duplicate of #124

**Closed as completed by X1nto** 2022-02-13 17:34 UTC
Labels: enhancement
