### ISSUE TITLE
Error downloading dark.apk / black.apk

### ISSUE THREAD

**Issue by 5yp10n** [YTVanced/VancedManager#649] opened 2021-08-09 06:43 UTC
Error downloading dark.apk or black.apk in Vanced Manager. IT seems like file is not available or server is down.

**Phone Specifications:**
- Brand: Xiaomi
- Operating System: MIUI 11
- Android Version: 9
- Vanced Manager Version: 2.6.0

**Please describe the problem you are having in as much detail as possible:**

**Steps to reproduce:**

**Further details:**

**Comment by agret** [comment] 2021-08-09 06:47
Duplicate of #648, #646, #645, #644 

The server is overloaded from everyone trying to update at once. Try again in a few hrs and it should be okay.

 #528 is proposed fix for this issue.

**Comment by Tomjohnsonellis** [comment] 2021-08-09 06:47
+1

Have installed the latest manager, MicroG install is fine but unable to install either of the vanced apks

**Comment by mon5termatt** [comment] 2021-08-09 06:49
People need to slow down

**Comment by LeeRyan9** [comment] 2021-08-09 06:50
Me too
![Uploading Screenshot_20210809-134917.png…]()

**Closed as completed** 2021-08-09 06:49 UTC
