### ISSUE TITLE
Can't go past "Welcome to Vanced Manager" screen

### ISSUE THREAD

**Issue by ayesse** [YTVanced/VancedManager#665] opened 2021-08-20 09:51 UTC
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Phone Specifications:**
- Brand: Samsung Galaxy Note Pro 12.2
- Operating System: Android 5.0.2 LRX22G.P905XXSABQB1
- Android Version: 5.0.2
- Vanced Manager Version: 2.6.0 Crimson

**Please describe the problem you are having in as much detail as possible:**

When I launch Vanced Manager I can't go past the first "Welcome to Vanced Manager" screen. Pressing the "Let's get started" button does absolutely nothing

**Steps to reproduce:**

**Further details:**

**Comment by X1nto** [comment] 2021-08-20 10:16
duplicate of #599

**Closed as completed by X1nto** 2021-08-20 10:16 UTC
