### ISSUE TITLE
manager won't download yt vanced

### ISSUE THREAD

**Issue by Ricardo199** [YTVanced/VancedManager#451] opened 2021-03-13 17:46 UTC
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisations

**Phone Specifications:**
- Brand: Samsung
- Operating System: android
- Android Version: 10
- Vanced Manager Version: latest

**Please describe the problem you are having in as much detail as possible:**
error while downloading dark or black theme when downloading youtube vanced

**Steps to reproduce:**
download the apk

**Further details:**
it doesn't matter if i change parametters it won't download

**Comment by X1nto** [comment] 2021-03-13 17:46
duplicate of #450

**Closed by X1nto** 2021-03-13 17:46 UTC
