### ISSUE TITLE
Vanced Manager unable to pull updates

### ISSUE THREAD

**Issue by ToxiClay** [YTVanced/VancedManager#505] opened 2021-04-26 02:12 UTC
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server ✔
- I am using the latest version ✔
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music) ✔
- This issue keeps re-occurring every time I try ✔

**Phone Specifications:**
- Brand: LG V20
- Operating System: Android
- Android Version: 8.0.0
- Vanced Manager Version: 2.5.1

**Please describe the problem you are having in as much detail as possible:**

Vanced Manager shows "Unavailable" for both Youtube Vanced and Vanced MicroG.

**Steps to reproduce:**

None.

**Further details:**

Deleting cache and app storage did not remedy the problem. The VancedApp website is responding.

**Comment by zarte13** [comment] 2021-04-26 02:13
Same issue on a
Brand: Oneplus N10 5G
Operating System: Android
Android Version: 10
Vanced Manager Version: 2.5.1

**Comment by chalkychelsea** [comment] 2021-04-26 02:16
Same Issue on a 
Brand: Google Pixel 3A
Operating System: Android
Android Version: 11
Vanced Manager Version: 2.5.1

**Comment by ReanSchwarzer1** [comment] 2021-04-26 02:17
Same issue on a
Brand: Samsung Galaxy A71
Operating System: Android
Android Version: 10
Vanced Manager Version: 2.5.1

**Comment by crazytil** [comment] 2021-04-26 02:17
Same issue on a 
Brand: Oneplus 8 Pro
Operating System: Android
Android Version: 11
Vanced Manager Version: 2.5.1

**Comment by BrunoSDomingues** [comment] 2021-04-26 02:19
Same issue on a
Brand: Samsung Galaxy Note20 Ultra
Operating System: Android
Android Version: 11
Vanced Manager Version: 2.5.1

**Comment by deathlyface** [comment] 2021-04-26 02:19
Same issue on a
Brand: Redmi Note 8 Pro
Operating System: Android
Android Version: 10
Vanced Manager Version: 2.5.1

**Comment by enriquewph** [comment] 2021-04-26 02:21
Same issue on a
Brand: Xiaomi Mi A2 Lite 4gb
Operating System: Android
Android Version: 10
Vanced Manager Version: 2.5.1

**Comment by PhilipReidy** [comment] 2021-04-26 02:22
Same issue on a
Brand: OnePlus 7 Pro
Operating System: Android
Android Version: 11
Vanced Manager Version: 2.5.1

**Comment by ValZapod** [comment] 2021-04-26 02:23
This is a very funny issue. It does work if you will update many times... LOL.

**Comment by Diatrix** [comment] 2021-04-26 02:24
> 
> 
> This is a very funny issue. It does work if you will update many times... LOL.

What do you mean?

**Comment by HunSul** [comment] 2021-04-26 02:25
Same issue on a
Brand: Samsung Galaxy A71 5G
Operating System: Android
Android Version: 11
Vanced Manager Version: 2.5.1

**Comment by ilhanyurek** [comment] 2021-04-26 02:25
Same issue on a
Brand: Samsung Galaxy A51
Operating System: Android
Android Version: 11
Vanced Manager Version: 2.5.1

**Comment by ValZapod** [comment] 2021-04-26 02:25
> What do you mean?

Well, swipe down.

**Comment by ZeroMe905** [comment] 2021-04-26 02:25
Same issue on a
Brand: Huawei Y5 2019
Operating System: Android
Android Version: 9
Vanced Manager Version: 2.5.1

**Comment by matthewhoendorf** [comment] 2021-04-26 02:28
> > This is a very funny issue. It does work if you will update many times... LOL.
> 
> What do you mean?

I think they got it to work after retrying the update many times. Likely a server issue.

**Comment by k5711628** [comment] 2021-04-26 02:32
Same issue on a
Brand: Google Pixel 5
Operating System: Android
Android Version: 11
Vanced Manager Version: 2.5.1
Vanced Version: root

**Comment by ValZapod** [comment] 2021-04-26 02:33
> Likely a server issue.

They are using https://mirror.codebucket.de/vanced/api/v1 it is insane if we managed to shut it down.

**Comment by ToxiClay** [comment] 2021-04-26 02:34
Right, well. It did let me update MicroG, then flipped back to Unavailable before I could try Vanced. Vanced is also broken now, so that's cool.

**Comment by GreyMariGaming** [comment] 2021-04-26 02:35
Same issue here
Brand: Realme 6 pro
Operating System: Android
Android Version: 10
Vanced Manager Version: 2.5.1(Weed)

**Comment by dprossner** [comment] 2021-04-26 02:37
Same issue on a pixel 4a 5g running android 11.
Logs look like this:
VMNetTools: https://vancedapp.com/api/v1/latest.json: 403
VMNetTools: Fetching using URL: https://mirror.codebucket.de/vanced/api/v1

**Comment by unshDee** [comment] 2021-04-26 02:37
Same issue
Brand: OnePlus 3T
Operating System: Android
Android Version: 9
Vanced Manager Version: 2.5.1(Weed)

**Comment by GTProgrammin** [comment] 2021-04-26 02:37
Same issue here
Brand: Realme 6 pro
Operating System: Android
Android Version: 10
Vanced Manager Version: 2.5.1(Weed)

**Comment by RaspberryKitty1** [comment] 2021-04-26 02:38
Same issue here
Brand: Samsung Galaxy J3 Luna Pro
Operating System: Android
Android Version: 6.0.1
Vanced Manager Version: 2.5.1(Weed)

**Comment by Lucasxyz9** [comment] 2021-04-26 02:39
Same issue on a
Brand: Oneplus 5T 
Operating System: Android
Android Version: 10
Vanced Manager Version: 2.5.1(Weed)

**Comment by AhRoon** [comment] 2021-04-26 02:40
Same issue, I hope this issue to be addressed.
Brand: Samsung Galaxy S20
Operating System: Android
Android Version: 11
Vanced Manager Version: 2.5.1(Weed)

**Comment by AhRoon** [comment] 2021-04-26 02:48
Seems I can connect to mirror, but the response from VancedManager is same and cannot be downloaded, we might need to wait until they fix the mirror completely.

**Comment by Girish1307** [comment] 2021-04-26 02:49
Same issue
Brand: Samsung Galaxy M40
Operating System: Android
Android Version: 11
Vanced Manager Version: 2.5.1(Weed)

**Comment by MysteriousLog6** [comment] 2021-04-26 02:51
Same issue:
Brand: Redmi Note 5 Pro/AI
Operating System: Android
Android Version: 11
Vanced Manager Version: 2.5.1(weed)

**Comment by vladistev** [comment] 2021-04-26 02:52
Same issue here. Is there a way to download the latest apks directly?
Brand: Samsung Galaxy S10
Operating System: Android
Android Version: 11
Vanced Manager Version: 2.5.1(Weed)

**Comment by cikeZ00** [comment] 2021-04-26 02:53
> Same issue here. Is there a way to download the latest apks directly?
> Brand: Samsung Galaxy S10
> Operating System: Android
> Android Version: 11
> Vanced Manager Version: 2.5.1(Weed)

You can use this to directly download the non-root version
https://mirror.codebucket.de/vanced/api/v1

**Comment by cikeZ00** [comment] 2021-04-26 02:56
![Screenshot_20210426-045538_Vanced_Manager.png](https://user-images.githubusercontent.com/17727672/116023029-aa9b6200-a64b-11eb-9f96-2906e476a8ad.png)

It managed to install just now for me.

**Comment by MysteriousLog6** [comment] 2021-04-26 02:56
> ![Screenshot_20210426-045538_Vanced_Manager.png](https://user-images.githubusercontent.com/17727672/116023029-aa9b6200-a64b-11eb-9f96-2906e476a8ad.png)
> 
> It managed to install just now for me.

Will try

**Comment by crazytil** [comment] 2021-04-26 02:56
Works now Everyone

**Comment by RaspberryKitty1** [comment] 2021-04-26 02:58
seems it working again

**Comment by Iron-E** [comment] 2021-04-26 03:04
Still doesn't let me dow load the root variant

**Comment by ToxiClay** [comment] 2021-04-26 03:14
> > Same issue here. Is there a way to download the latest apks directly?
> > Brand: Samsung Galaxy S10
> > Operating System: Android
> > Android Version: 11
> > Vanced Manager Version: 2.5.1(Weed)
> 
> You can use this to directly download the non-root version
> https://mirror.codebucket.de/vanced/api/v1

Which one would I need? There's a couple different files here. What's `black.apk` do specifically that the split_config APKs don't?

**Comment by ValZapod** [comment] 2021-04-26 03:16
> What's `black.apk` do specifically that the split_config APKs don't?

You must use splot apk everytime. It consists of black.apk, arm64.apk part and language.apk part. SAI installs all 3 apk.

**Comment by ToxiClay** [comment] 2021-04-26 03:17
> > What's `black.apk` do specifically that the split_config APKs don't?
> 
> You must use split apk everytime. It consists of black.apk, arm64.apk part and language.apk part. SAI installs all 3 apk.

Oh God, that sounds like trouble waiting to happen. I'm tech-savvy but not in this arena. How easy/hard is this to do?

**Comment by ValZapod** [comment] 2021-04-26 03:20
> Oh God, that sounds like trouble waiting to happen

What? Almost all Google Play apps are multiple apk (a.k.a. apks, a.k.a. split apk), not apk. One can even say apk is deprecated method since android 5.

> How easy/hard is this to do?

Very simple. Install SAI. https://play.google.com/store/apps/details?id=com.aefyr.sai

**Comment by ToxiClay** [comment] 2021-04-26 03:22
> > Oh God, that sounds like trouble waiting to happen
> 
> What? Almost all Google Play apps are multiple apk (a.k.a. apks, a.k.a. split apk), not apk. One can even say apk is deprecated method since android 5.

I meant specifically asking me to manually install a split APK is trouble, hence my mentioning my relative lack of savvy.

> > How easy/hard is this to do?
> 
> Very simple. Install SAI. https://play.google.com/store/apps/details?id=com.aefyr.sai

Oh. This makes me feel better! Thanks.

**Comment by X1nto** [comment] 2021-04-26 04:08
Is it fixed for everyone?

**Comment by Cris--** [comment] 2021-04-26 07:21
Nope, still never ending e.g. black.apk download. 10min / 5-7Mbit download transfer but didn't comes to the end!

Vanced Manager 2.6.9, crDroid 7.4 A11, Magisk 22.1

**Comment by ToxiClay** [comment] 2021-04-26 08:12
> [2021326_94119.log](https://github.com/YTVanced/VancedManager/files/6375202/2021326_94119.log)
> Nope, still never ending e.g. black.apk download. 10min / 5-7Mbit download transfer but didn't comes to the end!
> 
> Vanced Manager 2.6.9, crDroid 7.4 A11, Magisk 22.1, OnePlus 5T

How do you have Vanced Manager 2.6.9 when the most recent version is 2.5.1?

**Comment by Cris--** [comment] 2021-04-26 08:40
> How do you have Vanced Manager 2.6.9 when the most recent version is 2.5.1?

Updated by Vanced Manager it self..

**Comment by ValZapod** [comment] 2021-04-26 08:47
> How do you have Vanced Manager 2.6.9 when the

see https://github.com/YTVanced/VancedManager/issues/476#issuecomment-812451224 it was april 1 joke.

**Comment by Cris--** [comment] 2021-04-26 11:27
Uninstalled 2.6.9 april fool release. Installed 2.5.1 = Works! Don't know if this was the culprit here.

**Comment by X1nto** [comment] 2021-04-26 12:01
It seems like the problem is fixed. I'll close this issue, feel free to reopen if anyone still has problems

**Closed by X1nto** 2021-04-26 12:01 UTC
