### ISSUE TITLE
Downloads seems to be failing when trying to update

### ISSUE THREAD

**Issue by m4heshd** [YTVanced/VancedManager#648] opened 2021-08-09 06:41 UTC
**Phone Specifications:**
- Brand: OnePlus
- Operating System: Android (OxygenOS)
- Android Version: 11
- Vanced Manager Version: 2.6.0

**Please describe the problem you are having in as much detail as possible:**
Downloads fail when trying to update as shown here.

![image](https://user-images.githubusercontent.com/6711514/128668264-73a3cf00-4396-4e34-a1cc-eb772d07f063.png)

Been trying for hours. Network is good, the device is fine. Seems like an issue with the resource.

**Steps to reproduce:**
Try to update YT Vanced with following configs.

Theme: **Light + Black**
Version: **Latest**
Language: **English**

**Comment by agret** [comment] 2021-08-09 06:44
Duplicate of #646, #645, #644 

You are correct when you say "Seems like an issue with the resource" - the server is overloaded from everyone trying to update at once. Try again in a few hrs and it should be okay.

 #528 is proposed fix for this issue.

**Closed as completed** 2021-08-09 06:47 UTC
