### ISSUE TITLE
Cannot be Installable

### ISSUE THREAD

**Issue by doriandrey** [YTVanced/VancedManager#376] opened 2021-01-21 02:04 UTC
![Screenshot_20210121-083303](https://user-images.githubusercontent.com/51277594/105269971-59e71980-5bc3-11eb-9eb9-75bb060b8a95.jpg)
![Screenshot_20210121-082835](https://user-images.githubusercontent.com/51277594/105269976-5bb0dd00-5bc3-11eb-8d40-72566b5a935b.jpg)
 Help me! Please

**Comment by technic-Angel6644** [comment] 2021-01-21 03:20
Did you uninstall updates for YouTube?

**Comment by doriandrey** [comment] 2021-01-21 03:22
Android 11 built in default youtube newer than youtube vanced

**Comment by technic-Angel6644** [comment] 2021-01-21 03:24
Yea I just noticed it too, you're not the first with this issue

**Comment by technic-Angel6644** [comment] 2021-01-21 03:24
I'd advise you to use the microg version until Vanced version 16 is released

**Comment by doriandrey** [comment] 2021-01-21 03:26
Yes, I tried it.

**Comment by technic-Angel6644** [comment] 2021-01-21 03:40
If you want to, you could uninstall the stock youtube app completely, and then try installing vanced again

**Comment by joske** [comment] 2021-01-21 09:52
duplicate of #375

**Comment by X1nto** [comment] 2021-01-21 11:02
This is weird tbh, manager should uninstall stock youtube if it detects stock youtube with higher version. Might be something wrong with uninstaller

**Comment by joske** [comment] 2021-01-21 11:27
In my case youtube is an app in product partition. It can't be uninstalled.

**Comment by doriandrey** [comment] 2021-01-21 11:28
I'm running on Oxygen OS 11 Beta

**Comment by X1nto** [comment] 2021-01-23 10:31
Duplicated from #375: It appears that youtube is installed in /system/product/, those apps can't be uninstalled via pm (which is what Manager is trying to do). the solution here would be to wait for a new Vanced update

**Closed by X1nto** 2021-01-23 10:31 UTC
