### ISSUE TITLE
App data gets cleared when update/reinstall

### ISSUE THREAD

**Issue by ghost** [YTVanced/VancedManager#657] opened 2021-08-11 10:25 UTC
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Phone Specifications:**
- Brand: Google Pixel 4a
- Operating System: Android
- Android Version: 11
- Vanced Manager Version: 2.6.0

**Please describe the problem you are having in as much detail as possible:**
Vanced Manager clears out app data of Youtube/Vanced when you update or reinstall Vanced. This is quite annoying because you need to setup everything from scratch again and again

**Steps to reproduce:**
1. Reinstall Youtube Vanced

**Further details:**
If it's not possible to prevent this issue, can you at least make it backup the data and restore automatiacally after install?

**Comment by X1nto** [comment] 2021-08-11 11:01
Duplicate of #621

**Closed as completed by X1nto** 2021-08-11 11:01 UTC

**Comment by ghost** [comment] 2021-08-11 11:14
Oh i didn't saw it

**Comment by Girhi** [comment] 2021-08-11 15:11
I don't care just leave me the fuck alone.

Em qua, 11 de ago de 2021 08:15, VanHoevenTR ***@***.***>
escreveu:
