### ISSUE TITLE
[ROOT] Youtube vanced not working after rebooting (NullPointerException log included)

### ISSUE THREAD

**Issue by YellowZaki** [YTVanced/VancedManager#340] opened 2021-01-03 01:01 UTC
**Phone Specifications:**
- Brand: Xiaomi Mi 10 Lite
- Operating System: Miui 12.1 
- Android Version: Android 11
- Vanced Manager Version: 2.1.0

**Please describe the problem you are having in as much detail as possible:**

First of all: root method.

Before updating to Android 11, vanced youtube was working fine. After upgrading to Android 11, youtube vanced was being uninstalled on reboot so I upgraded to the new Vanced Manager Version. Now I have another problem: every time I open youtube after reboot, I get this crash report (in addition, the app icon changes to normal youtube instead of vanced):
https://pastebin.com/RLB3EEKh

**Steps to reproduce:**
1. Install youtube vanced via vanced manager. Youtube vanced is correctly installed and launching fine. The app icon is youtube vanced.
2. Reboot the phone
3. Youtube app icon is now original youtube instead of vanced and when I try to open it, it won't. 

**Further details:**
I'm using Magisk module: terminal-debloater in order to uninstall the original youtube because it is a system app. If I don't do this, I can't install youtube vanced because it tells me to downgrade but I can't downgrade because youtube is a system app and even uninstalling app updates, its version in above youtube vanced version.
I was already using this before Android 11 update when youtube vanced was working perfectly, so I guess this is not the problem.

**Comment by YellowZaki** [comment] 2021-01-03 02:49
More details:
It seems on reboot, base.apk inside data/adb/Vanced is getting corrupted or something like that.
When I install youtube vanced, I can click on base.apk and it prompts me to install it. After rebooting, when I click on the base.apk, it is like an irecognizable apk.

**Comment by Crescendo-BLYAT** [comment] 2021-01-05 17:41
Exactly the same on my other Redmi Note 8 Pro, I have 2 with exact same config & OS version & Magisk latest canary.

One of my RN8Pro is normal, strange eh?

**Comment by itsbarker23** [comment] 2021-01-06 15:12
Make sure you have play store auto update off for youtube  if you are having issues with the latest versions try an older version to see if you have the same issue. Micro g could be an issue here and you can try to downgrade that as well. Clear cache and data, then remove youtube vanced and music through the manager. If it doesn't disappear on your phone see if you have to manually uninstall them. If they are system apps I recommend downloading lucky patcher and uninstalling them. Through twrp I would flash magisk youtube uninstaller (google XDA youtube universal uninstaller magisk), Wipe dalvik and cache through twrp reboot and download youtube vanced again through vanced manager. 

I had an issue with a magisk module not correctly working, I had to downgrade from 20 to 16 and it's working fine. Maybe last resort downgrade magisk. (Download magisk uninstaller flashable) reboot into recovery after and flash whichever magisk version you're going to use. Wipe dalvik and cache / reboot

**Comment by Crescendo-BLYAT** [comment] 2021-01-07 05:02
@itsbarker23 wait, microG what?
This is root method which doesn't even require microG to begin with.

And Magisk is latest canary build 21201.

Also Play Store update always off.

**Comment by kyelbek** [comment] 2021-01-09 21:14
First of all, this log is pretty much useless. There's probably about 15 or more lines above of what you attached which would define this problem better, java stacktrace alone is usually not enough.
But, since this stacktrace is exactly the same as mine, the issue is most probably what I encountered and fixed in [this PR](https://github.com/YTVanced/VancedManager/pull/345).
Secondly, don't touch apks, or other files, in these directories on your own. They're not intended to be executed directly/installed.

Try [this build](https://github.com/kyelbek/VancedManager/releases/download/test/app-debug.apk) and report back. Be cautious though, this app build might not be ready for production yet and can contain some unexpected bugs. I fixed broken parts that were required for proper installation and tested it myself, so it should be solid. So far, 1 person tested it, aside from me, and result was positive.

If it'll be still breaking for you guys, take new logcats and put them here.

**Comment by haraesh** [comment] 2021-01-10 13:04
@kyelbek, I was having the same issue as OP, but on Android 10 (Oxygen OS). I am using the root version. First time I tried (pre 2.1.0) on reboot Vanced would disappear and a reinstall from the manager would fix it. On 2.1.0 on reboot the app would still be on the home screen but will crash. Again a reinstall will fix it. Tried your debug build and I can confirm Vanced works across a reboot. Didn't notice any other issues so far. 

Device: OnePlus 7T Pro (Mclaren edition)
OS: OOS 10 Open Beta 6

**Comment by X1nto** [comment] 2021-01-10 13:38
This issue is most likely fixed in 8be35fec739401130fc7899512301329ad191259 and 04fc790e365ae5c35d9a55afc28a96ce820d58bb, just wait for an update

**Comment by X1nto** [comment] 2021-01-10 13:38
sorry, closed by accident

**Comment by Crescendo-BLYAT** [comment] 2021-01-11 16:35
@kyelbek your debug build fixed everything! ☺️
Thanks a lot, now waiting for official release...

**Comment by DeltaSingh** [comment] 2021-01-15 12:41
> First of all, this log is pretty much useless. There's probably about 15 or more lines above of what you attached which would define this problem better, java stacktrace alone is usually not enough.
> But, since this stacktrace is exactly the same as mine, the issue is most probably what I encountered and fixed in [this PR](https://github.com/YTVanced/VancedManager/pull/345).
> Secondly, don't touch apks, or other files, in these directories on your own. They're not intended to be executed directly/installed.
> 
> Try [this build](https://github.com/kyelbek/VancedManager/releases/download/test/app-debug.apk) and report back. Be cautious though, this app build might not be ready for production yet and can contain some unexpected bugs. I fixed broken parts that were required for proper installation and tested it myself, so it should be solid. So far, 1 person tested it, aside from me, and result was positive. Remove previous version of Manager before installing this and reinstall YT Vanced with this one.
> 
> If it'll be still breaking for you guys, take new logcats and put them here.

Still having the same issue, no change with this build

**Comment by kyelbek** [comment] 2021-01-15 14:08
> Still having the same issue, no change with this build

Remember to try to open the app like 2 times while taking this logcat. If you want, you can also try switching your SELinux to permissive when app is already broken, and check if it launches properly in such case.

**Comment by X1nto** [comment] 2021-01-19 09:35
Checkout 2.2.1, if that fixes the crash, please close this issue

**Comment by X1nto** [comment] 2021-01-22 13:29
I'm considering this fixed. If anyone still has the issue, feel free to comment and I'll reopen

**Closed by X1nto** 2021-01-22 13:29 UTC
